spring.application.name=Statystyka

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Statystyka}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:Javed}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kuba}
spring.datasource.driver-class-name=org.postgresql.Driver

app.bootstrap.admin.username=${APP_BOOTSTRAP_ADMIN_USERNAME:admin}
app.bootstrap.admin.email=${APP_BOOTSTRAP_ADMIN_EMAIL:test@abc.pl}
app.bootstrap.admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:TymczasoweHaslo123!}

logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR
logging.level.org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver=ERROR
logging.level.org.springframework.web=ERROR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.from=${SPRING_MAIL_FROM:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.ssl.trust=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST:smtp.gmail.com}
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT:60000}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT:60000}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT:60000}

server.servlet.session.timeout=1h